language: cpp

sudo: required

matrix:
  include:
    - { os: linux, dist: trusty, compiler: gcc }
    - { os: linux, dist: trusty, compiler: clang }
    - { os: osx, compiler: gcc }
    - { os: osx, compiler: clang }

script:
  - cd ESCParser
  - make
  - cd ../Sav2Cartridge
  - make
  - cd ../sav2wav
  - make
  - cd ../rt11dsk
  - make
  - cd ../SavDisasm
  - make
