language: cpp

os:
  - linux
  - osx
dist: trusty
sudo: required
compiler: gcc

script:
  - cd ESCParser
  - make
  - cd ../Sav2Cartridge
  - make
  - cd ../sav2wav
  - make
  - cd ../rt11dsk
  - make
  - cd ../SavDisasm
  - make
